### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)

### ISSUE THREAD

**Issue by Berzrk** [tuguangquan/mybatis#30]
按照文档教程调试一直报错
配置文件如下
![image](https://user-images.githubusercontent.com/36788336/186119411-36b539dd-eeb1-4400-82f5-a14782e8e487.png)
![image](https://user-images.githubusercontent.com/36788336/186119464-e7f0dec7-def5-491f-a8ae-5314aabbed00.png)
![image](https://user-images.githubusercontent.com/36788336/186119511-ccf75b08-0e91-478f-82e6-2d6a1d21268b.png)
打包之后显示文件正常
![image](https://user-images.githubusercontent.com/36788336/186119604-69242289-fcf7-472c-b9fe-845eeae0f281.png)

**Comment by Berzrk** [comment]
> 

idea

**Comment by YuJF2J** [comment]
来信已收到
