### ISSUE TITLE
pom.xml dependency problems

### ISSUE THREAD

**Issue by wangqinggo** [tuguangquan/mybatis#7]
many dependency  not found

**Comment by zqpx** [comment]
你是个菜鸡

**Comment by tuguangquan** [comment]
你是有病吗


------------------



涂光权
武汉理工大学


 联系我









 




------------------ 原始邮件 ------------------
发件人: "zqpx"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:47
收件人: "tuguangquan/mybatis"<mybatis@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [tuguangquan/mybatis] pom.xml dependency problems (#7)




你是个菜鸡

**Comment by xiongyouqiang** [comment]
你们对嘛 怎么还发到我这里来了，差点以为我得罪谁了，可以私下开骂 ，不要伤及无辜




------------------ 原始邮件 ------------------
发件人: "tgq"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:49
收件人: "tuguangquan/mybatis"<mybatis@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [tuguangquan/mybatis] pom.xml dependency problems (#7)



你是有病吗 
 
 
 ------------------ 
 
 
 
 涂光权 
 武汉理工大学 
 
 
  联系我 
 
 
 
 
 
 
 
 
 
   
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "zqpx"<notifications@github.com>; 
 发送时间: 2019年8月8日(星期四) 下午4:47 
 收件人: "tuguangquan/mybatis"<mybatis@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: Re: [tuguangquan/mybatis] pom.xml dependency problems (#7) 
 
 
 
 
 你是个菜鸡

**Comment by tang1998bjt** [comment]
为啥我会收到这封邮件?

**Comment by xiongyouqiang** [comment]
应该是你订阅了吧 




------------------ 原始邮件 ------------------
发件人: "tang1998bjt"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:52
收件人: "tuguangquan/mybatis"<mybatis@noreply.github.com>;
抄送: "小强"<657619673@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [tuguangquan/mybatis] pom.xml dependency problems (#7)




为啥我会收到这封邮件?

**Comment by teartao** [comment]
因为大家都watch 了   [tuguangquan/mybatis]   项目  所以会收到 开发 和 “沟通”消息




------------------ 原始邮件 ------------------
发件人: "tang1998bjt"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午4:52
收件人: "tuguangquan/mybatis"<mybatis@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [tuguangquan/mybatis] pom.xml dependency problems (#7)




为啥我会收到这封邮件?
